### ISSUE TITLE
Error registering client

### ISSUE THREAD

**Issue by qafro1** [wdahlenburg/interactsh-collaborator#14]
java.lang.RuntimeException: java.net.UnknownHostException: interact.sh
Error registering client

at burp.Zj6f.makeHttpRequest(Unknown Source)
	at interactsh.Client.registerClient(Client.java:67)
	at burp.listeners.InteractshListener$1.run(InteractshListener.java:27)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: interact.sh

**Comment by wdahlenburg** [comment]
@qafro1 ProjectDiscovery has a list of public servers on https://github.com/projectdiscovery/interactsh#using-self-hosted-server. An update was made to use the Montoya API (v1.0.2). Can you test that out, which should use `oast.pro` as the default server?

**Comment by dneel-parikh** [comment]
I'm getting the same error from the extension:

![image](https://github.com/wdahlenburg/interactsh-collaborator/assets/152416954/e7d20a5f-9dd8-455e-9fbb-92c39899f12b)
